"""created two more file fields

Revision ID: 6be97dfbe8af
Revises: ac4f662cb1e1
Create Date: 2024-04-02 22:53:17.022009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be97dfbe8af'
down_revision = 'ac4f662cb1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subheading_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thirdlevel_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('thirdlevel_image')
        batch_op.drop_column('subheading_image')

    # ### end Alembic commands ###
